---
- name: Deploy docker app on server
  hosts:
    - usa4foryou-server
  become: true
  tasks:
    - name: Container present
      register: output
      community.docker.docker_container:
        name: usa4foryou-backend
        pull: always
        state: healthy
        image: botirkhuja/usa-4-for-you-backend:latest
        recreate: true
        restart_policy: unless-stopped
        restart_retries: 3
        comparisons:
          image: strict
        ports:
          - 8083:8083
        env:
          DB_URL: "{{ lookup('env', 'DB_URL') }}"
          DB_USERNAME: "{{ lookup('env', 'DB_USERNAME') }}"
          DB_PASSWORD: "{{ lookup('env', 'DB_PASSWORD') }}"
          DB_LOGGING: "INFO"
          MINIO_URL: "{{ lookup('env', 'MINIO_URL') }}"
          MINIO_ACCESS_NAME: "{{ lookup('env', 'MINIO_ACCESS_NAME') }}"
          MINIO_ACCESS_SECRET: "{{ lookup('env', 'MINIO_ACCESS_SECRET') }}"
          MINIO_BUCKET_NAME: "{{ lookup('env', 'MINIO_BUCKET_NAME') }}"
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8083/api/health"]
          interval: 5s
          timeout: 5s
          retries: 2
          start_period: 3s

    - name: Show results
      ansible.builtin.debug:
        var: output
        
